package com.javarush.task.task04.task0429;

import java.io.*;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
/*                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
Положительные и отрицательные числа                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

public class Solution {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    public static void main(String[] args) throws Exception {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        int a = Integer.parseInt(reader.readLine());
        int b = Integer.parseInt(reader.readLine());
        int c = Integer.parseInt(reader.readLine());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        if (a > 0 && b > 0 && c > 0) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        System.out.println("количество положительных чисел: "+3);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        System.out.println("количество отрицательных чисел: "+0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        else if (a < 0 && b < 0 && c < 0) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        System.out.println("количество положительных чисел: "+0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        System.out.println("количество отрицательных чисел: "+3);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        }
        else if (a > 0 && b > 0 && c < 0) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        System.out.println("количество положительных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        else if (a > 0 && c > 0 && b < 0) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        System.out.println("количество положительных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        else if (b > 0 && c > 0 && a < 0) {
        System.out.println("количество положительных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        else if (a > 0 && b < 0 && c < 0) {
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        System.out.println("количество отрицательных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        else if (b > 0 && a < 0 && c < 0) {
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        System.out.println("количество отрицательных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        else if (c > 0 && a < 0 && b < 0) {
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        System.out.println("количество отрицательных чисел: "+2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        else if (a == 0 && b < 0 && c == 0 || a == 0 && b == 0 && c < 0 || a < 0 && b == 0 && c == 0) {
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                      
        else if (a == 0 && b > 0 && c > 0 || a > 0 && b == 0 && c > 0 || a > 0 && b > 0) {
        System.out.println("количество отрицательных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+2);                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
        else if (a < 0 && b < 0 || a == 0 && b < 0 && c < 0 || a < 0 && b == 0 && c < 0) {
        System.out.println("количество отрицательных чисел: "+2);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
        else if (a == 0 && b > 0 && c == 0 || a == 0 && b == 0 && c > 0 || a > 0 && b == 0 && c == 0) {                                                                                                                                                                                                                                                                                                            
        System.out.println("количество отрицательных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                                                                                                                              
        else if (a == 0 && b == 0) {
        System.out.println("количество отрицательных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+0);                                                                                                                                                                                                                                                                                                            
        }
        else if (a == 0 && b < 0 || a > 0) {
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        }
        else {
        System.out.println("количество отрицательных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        System.out.println("количество положительных чисел: "+1);                                                                                                                                                                                                                                                                                                            
        }//напишите тут ваш код
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
}